import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Arweave from "arweave";
import { WarpFactory } from 'warp-contracts'

const arweave = Arweave.init({
  host: "arweave.net",
  port: 443,
  protocol: "https"
})

const CONTRACT_SRC = "KNuF1-S_5vd0mrPc1X2CDCvaC-3cbK8Y476aXYQ5QkI"

export default function Home() {
  const warp = WarpFactory.forMainnet();
  const contract = warp.contract(CONTRACT_SRC).connect();
  const handleClick = async () => {
    const { cachedValue } = await contract.readState();

    console.log('state: ', cachedValue)
    alert("CLICKED")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleClick}>Click Me</button>
      </main>
    </div>
  )
}
