import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { WarpFactory } from 'warp-contracts'

// Replace with your own
const CONTRACT_SRC = "FR2irQXRvXL2MC5aHoNSNcCW_LZYmyE50xNFtISb5AI"

export default function Home() {
  const [clicks, setClicks] = useState();
  const warp = WarpFactory.forMainnet();
  const contract = warp.contract(CONTRACT_SRC).connect();
  // Reads contract state and sets `clicks` variable
  const getClicks = async () => {
    const { cachedValue } = await contract.readState();
    setClicks(cachedValue.state.clicks)
  }

  const addClick = async () => {
    // 
    try {
      setClicks('updating...')
      await contract.writeInteraction({
        function: "click",
      })
      getClicks()
    }
    catch (error) {
      console.log(error)
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button onClick={getClicks}>Get clicks</button>
          <button onClick={addClick}>Add View</button>
        </div>
        <div>
          {clicks && <p>{clicks} clicks</p>}
        </div>
      </main>
    </div>
  )
}
